---
title: "FAO VoI" 
subtitle: "Tuna RFMO datasets"
author: "Laurence Kell"
output: rmarkdown:::html_document
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEncoding{UTF-8}
tags: FLPKG FLR
license: Creative Commons Attribution-ShareAlike 4.0 International
---
  
```{r knitr_init, echo=FALSE, results="hide"}
library(knitr)
## Global options
opts_chunk$set(echo    =FALSE,
               eval    =TRUE,
               cache   =TRUE,
               cache.path="cache/data/trfmo",
               prompt  =FALSE,
               comment =NA,
               message =FALSE,
               tidy    =FALSE,
               warning =FALSE,
               fig.height=6,
               fig.width =10,
               fig.path  ="../tex/figs/trfmo-",
               dev       ="png")

options(digits=3)

iFig=0
```

```{r, pkgs, echo=FALSE, message=FALSE}
library(reshape)
library(plyr)
library(dplyr)
library(ggplot2)
library(kobe)

library(FLCore)
library(FLife)

library(diags)
library(r4ss)
```

```{r, dir, echo=FALSE, message=FALSE}
dirMy ="/home/laurence-kell/Desktop/papers/COM"
dirInp=file.path(dirMy,"inputs") 
dirDat=file.path(dirMy,"data")
dirRes=file.path(dirMy,"results")
```


```{r, tRFMO,eval=FALSE}
setRAM<-function(x){
  rf =getRf(x)
  sp =spFunc(x)[-1,]
  res=transform(sp,stock=ssb/rf[1,"ssbmsy"])
  res=cbind(res,"harvest"=x$Kobe[seq(dim(res)[1]),3])
  res}

dir   =system2("ls",args=dirAss,stdout=TRUE)
dir=dir[dir.exists(file.path(dirAss,dir))]
dir=dir[file.exists(file.path(dirAss,dir,"lkout.rdata"))]

jb=mdply(dir,function(x) {
     load(file.path(dirAss,x,"lkout.rdata"))
     cbind(assessid=x,lkout)})[,-1]

jb$assessid=jb$stockid

ss=data.frame(
file=c(file.path(c("/home/laurence-kell/Dropbox/xval/io-bet",
                   "/home/laurence-kell/Dropbox/xval/io-yft",
                   "/home/laurence-kell/Dropbox/xval/epo-bet",
                   "/home/laurence-kell/Dropbox/xval/epo-yft",
                   "/home/laurence-kell/Dropbox/xval/iccat-bet",
                   "/home/laurence-kell/Dropbox/xval/iccat-yft"),"base"),
  file.path("/home/laurence-kell/Desktop/rfmo/iccat/sc-eco/2020/inputs/ss",c("sma/2019/run1",
                                                                             "bum/2018",
                                                                             "whm/2019/run6",
                                                                             "swon/2017/run1"))),
assessid=c("io-bet","io-yft","epo-bet","epo-yft","iccat-bet","iccat-yft","iccat-sma","iccat-bum","iccat-whm","iccat-swo"),
species=c("Thunnus obesus","Thunnus albacares",
          "Thunnus obesus","Thunnus albacares",
          "Thunnus obesus","Thunnus albacares",
          "Isurus oxyrinchus",
          "Makaira nigricans",
          "Kajikia albida",
          "Xiphias gladius"))
dat=ldply(dlply(ss,.(assessid,species), with, getSS(file)),getTs)

dt1=ddply(transform(cbind(subset(dat,assessid%in%ss[1:4,2]),qrtr=1:4),year=year-qrtr),.(assessid,species,year), with, 
             data.frame(year=(year[1]+3)/4,stock=stock[1],harvest=harvest[1],biomass=biomass[1],ssb=ssb[1],catch=sum(catch)))
ss=rbind.fill(dt1,subset(dat,!assessid%in%unique(dt1$assessid)))
trfmo=rbind.fill(ss,jb)
#trfmo=rbind(ddply(subset(trfmo,year<1000),.(assessid),transform, year=year+2018-max(year)),
#            subset(trfmo,year>1000))

nms=data.frame(
assessid=c("iccat-bet","epo-bet","io-bet",
           "iccat-yft","epo-yft","io-yft",
           "albsatl_iccat",
           "iccat-swo","swo_iotc","swo_natl","swo_satl","swomed_iccat",
           "iccat-bum","bum_iccat","bum_iotc",
           "iccat-whm","whm_iccat",
           "mls_iotc",
           "skj_iotc",
           "smanatl_iccat","iccat-sma",
           "bsh_iotc"),
species=c("Thunnus obesus","Thunnus obesus","Thunnus obesus",
          "Thunnus albacares","Thunnus albacares","Thunnus albacares",
          "Thunnus alalunga",
          "Xiphias gladius","Xiphias gladius","Xiphias gladius","Xiphias gladius","Xiphias gladius",
          "Makaira nigricans","Makaira nigricans","Makaira nigricans",
          "Kajikia albida","Kajikia albida",
          "Kajikia audax",
          "Katsuwonus pelamis",
          "Isurus oxyrinchus","Isurus oxyrinchus",
          "Prionace glauca"))
trfmo=rbind.fill(transform(ss,stockid=paste(assessid,"ss",sep="-")),
                 transform(jb,stockid=paste(assessid,"jabba",sep="-")))
trfmo=merge(trfmo[,-2],nms,by="assessid")
trfmo=ddply(trfmo,.(assessid), transform, year=year+ifelse(max(year),2018-max(year),0))

save(trfmo,file=file.path(dirDat,"trfmo.RData"))
```


```{r}
load(file=file.path(dirDat,"trfmo.RData"))

ggplot(trfmo)+
  geom_line(aes(year,stock))+
  facet_wrap(~assessid,scale="free")+
  theme_bw()+
  xlab("Year")+ylab(expression(B:B[MSY]))
```

